---
CompileFlags:
    Add: [-xc++, -std=c++17, -Wall, -Wextra, -Wno-pmf-conversions, -I/usr/include, -I/usr/include/c++/13, -I/usr/include/x86_64-linux-gnu, -I/usr/include/x86_64-linux-gnu/c++/13 ]
    Compiler: clang++

Diagnostics:
  ClangTidy:
    Remove: modernize*
    CheckOptions:
      readability-identifier-naming.VariableCase: CamelCase
